### ISSUE TITLE
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'verify_ssl'

### ISSUE THREAD

**Issue by hughbe** [megadose/nqntnqnqmb#4]
I'm executing the following python code:

```py
from nqntnqnqmb import *
```

However, I get an error:
```
PS C:\source\repos\linkedin-scraper> python .\linkedin-scraper.py
Traceback (most recent call last):
  File "C:\source\repos\linkedin-scraper\linkedin-scraper.py", line 5, in <module>
    from nqntnqnqmb import *
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nqntnqnqmb\__init__.py", line 1, in <module>
    from nqntnqnqmb.core import *
  File "C:\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\nqntnqnqmb\core.py", line 5, in <module>
    ua = UserAgent(verify_ssl=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'verify_ssl'
```

Could you please advise?

**Comment by hughbe** [comment]
Fix is to downgrade `fake-useragent`: 
https://github.com/fake-useragent/fake-useragent/blob/e58c42bd57b59dc42b455f1463c39ab0172db1b0/README.md?plain=1#L201C1-L202C1
