### ISSUE TITLE
KeyError: 'paging'

### ISSUE THREAD

**Issue by azizmhmmdf** [megadose/nqntnqnqmb#5]
try:
        r = requests.get(url, cookies=cookies, headers=headers, timeout=60)
    except Exception:
        exit()
        
    try:
        content = json.loads(r.text)
    except:
        return(r.text)

    print(content) -> {'status': 404}   
    
  Traceback (most recent call last):
  File "/home/be-azizmuhammadf/Documents/E-bdesk/Project/2024/linkedin/main.py", line 129, in <module>
    main()
  File "/home/be-azizmuhammadf/Documents/E-bdesk/Project/2024/linkedin/main.py", line 122, in main
    results = getProfileFromName(search_string, config["JSESSIONID"],config["li_at"])
  File "/home/be-azizmuhammadf/Documents/E-bdesk/Project/2024/linkedin/main.py", line 48, in getProfileFromName
    data_total = content['paging']['total']
KeyError: 'paging'

**Comment by SuperSayf** [comment]
I am getting the same error

```
Traceback (most recent call last):
  File "/Users/***/Downloads/nqntnqnqmb-master/nqntnqnqmb.py", line 67, in <module>
    result= getProfileFromName(profile,config["JSESSIONID"],config["li_at"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/***/Downloads/nqntnqnqmb-master/nqntnqnqmb/core.py", line 60, in getProfileFromName
    data_total = content['paging']['total']
                 ~~~~~~~^^^^^^^^^^
KeyError: 'paging'
```

**Comment by JackBlair87** [comment]
I don't think this library works after LinkedIn updated their CSS recently. Here was my approach: https://medium.com/@jackblair87/writing-a-live-follower-count-python-program-for-my-website-5e34631582d3
